### ISSUE TITLE
大哥，有方式联系吗

### ISSUE THREAD

**Issue by forwells** [d-mod/avatar#2]
我比较喜欢DNF，想学学模型制作~我这边也有服务器资源，感觉纸娃娃的系统太卡了， 我可以托管 方便的话可以留个wx或者邮箱交流一下

**Comment by Kritsu** [comment]
github国内连接不太行，正准备迁移到gitee上。托管的话部署gh-pages分支就行了

**Comment by Kritsu** [comment]
学一下 nginx配置就行了 gh-pages分支是已经打包好的

**Comment by forwells** [comment]
> 学一下 nginx配置就行了 gh-pages分支是已经打包好的

是的
![image](https://user-images.githubusercontent.com/32950945/146915440-b4799c57-366b-4b62-813e-4a88c78cd319.png)

我先看下需不需要反向代理

**Comment by forwells** [comment]
![image](https://user-images.githubusercontent.com/32950945/146921277-440429b1-c715-43bf-93cc-7f4b9883103c.png)
nginx 有点麻烦 不过还好
