### ISSUE TITLE
大兄弟，2023年的时装能扒么  或者你没有时间给我说下资源文件一般从哪里来吗，我去提一下PR

### ISSUE THREAD

**Issue by Henrycheheng** [d-mod/avatar#4]

**Comment by chizukicn** [comment]
贴图:
  游戏目录/ImagePacks2/sprite_character_{职业}_{第二性别职业?"at":""}equipment_avatar_[部位].NPK。
图标:
  游戏目录/ImagePacks2/sprite_item_avatar_{第二性别职业?"at"+职业:职业}.NPK

备注:
  第二性别职业指同一职业中后登场的性别，例如鬼剑士的女鬼剑士，格斗家的男格斗家
  资源文件提交到[Avatar_Resource](https://github.com/d-mod/avatar_resource)这个仓库
  工具在[ExtractorSharp](https://github.com/d-mod/ExtractorSharp/releases/download/v1.7.3.0/ExtractorSharp-1.7.3.0.zip)

**Comment by Henrycheheng** [comment]
> 

DNF
